### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by rxaviers**

### CODE REVIEW

**Comment by rxaviers** [comment]
It uses a simplified version of commitplease https://github.com/rxaviers/commitplease/compare/b3.0.0

**Comment by jzaefferer** [comment]
Do you have a suggestion what to do with that simplified version of commitplease? Based on how commitplease is currently used, its not just simplified, but also crippled.

**Comment by rxaviers** [comment]
I suggest decoupling the validation from the git hook. They address two different problems. The former is a dependency of the latter.

**Comment by rxaviers** [comment]
The former is a dependency of the latter.

**Pull request closed without merging**
